# 여기에 발급받은 Google API 키를 붙여넣으세요.
GOOGLE_API_KEY = "AIzaSyBXyT7b_ZkeMxLEPfIbHmrT4EwQEQjqJDc"

# 새로 추가할 앱 접속 비밀번호
APP_PASSWORD = "chery2025!"

# 새로 추가할 쿠키 암호화용 키
COOKIE_ENCRYPTION_KEY = "q1w2e3r4t5y6u7i8o9p0"
